// <auto-generated />
namespace PI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Sum_in_Invoive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Sum_in_Invoive));
        
        string IMigrationMetadata.Id
        {
            get { return "201610021949590_add_Sum_in_Invoive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
