namespace PI.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SetMaxLengthforproperties : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.RoleHierarchies");
            AlterColumn("dbo.AccountSettings", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Customers", "Salutation", c => c.String(maxLength: 5));
            AlterColumn("dbo.Customers", "FirstName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Customers", "MiddleName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Customers", "LastName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Customers", "Email", c => c.String(maxLength: 256));
            AlterColumn("dbo.Customers", "SecondaryEmail", c => c.String(maxLength: 256));
            AlterColumn("dbo.Customers", "PhoneNumber", c => c.String(maxLength: 20));
            AlterColumn("dbo.Customers", "MobileNumber", c => c.String(maxLength: 20));
            AlterColumn("dbo.Customers", "JobCapacity", c => c.String(maxLength: 100));
            AlterColumn("dbo.Customers", "SelectedColour", c => c.String(maxLength: 50));
            AlterColumn("dbo.Customers", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Addresses", "Country", c => c.String(maxLength: 2));
            AlterColumn("dbo.Addresses", "ZipCode", c => c.String(maxLength: 10));
            AlterColumn("dbo.Addresses", "Number", c => c.String(maxLength: 10));
            AlterColumn("dbo.Addresses", "City", c => c.String(maxLength: 100));
            AlterColumn("dbo.Addresses", "State", c => c.String(maxLength: 50));
            AlterColumn("dbo.Addresses", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Tenants", "TenancyName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Tenants", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.UserInDivisions", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Divisions", "Name", c => c.String(maxLength: 100));
            AlterColumn("dbo.Divisions", "Type", c => c.String(maxLength: 6));
            AlterColumn("dbo.Divisions", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Companies", "Name", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "COCNumber", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "VATNumber", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "CompanyCode", c => c.String(maxLength: 100));
            AlterColumn("dbo.Companies", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.CostCenters", "Name", c => c.String(maxLength: 100));
            AlterColumn("dbo.CostCenters", "PhoneNumber", c => c.String(maxLength: 20));
            AlterColumn("dbo.CostCenters", "Type", c => c.String(maxLength: 6));
            AlterColumn("dbo.CostCenters", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.DivisionCostCenters", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Currencies", "CurrencyCode", c => c.String(maxLength: 10));
            AlterColumn("dbo.Currencies", "CurrencyName", c => c.String(maxLength: 10));
            AlterColumn("dbo.Currencies", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Languages", "LanguageCode", c => c.String(maxLength: 2));
            AlterColumn("dbo.Languages", "LanguageName", c => c.String(maxLength: 15));
            AlterColumn("dbo.Languages", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.TimeZones", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.VolumeMetrics", "Name", c => c.String(maxLength: 5));
            AlterColumn("dbo.VolumeMetrics", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.WeightMetrics", "Name", c => c.String(maxLength: 5));
            AlterColumn("dbo.WeightMetrics", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.AddressBooks", "CompanyName", c => c.String(maxLength: 100));
            AlterColumn("dbo.AddressBooks", "UserId", c => c.String(maxLength: 50));
            AlterColumn("dbo.AddressBooks", "Salutation", c => c.String(maxLength: 5));
            AlterColumn("dbo.AddressBooks", "FirstName", c => c.String(maxLength: 100));
            AlterColumn("dbo.AddressBooks", "LastName", c => c.String(maxLength: 100));
            AlterColumn("dbo.AddressBooks", "EmailAddress", c => c.String(maxLength: 256));
            AlterColumn("dbo.AddressBooks", "PhoneNumber", c => c.String(maxLength: 20));
            AlterColumn("dbo.AddressBooks", "AccountNumber", c => c.String(maxLength: 100));
            AlterColumn("dbo.AddressBooks", "Country", c => c.String(maxLength: 2));
            AlterColumn("dbo.AddressBooks", "ZipCode", c => c.String(maxLength: 10));
            AlterColumn("dbo.AddressBooks", "Number", c => c.String(maxLength: 10));
            AlterColumn("dbo.AddressBooks", "City", c => c.String(maxLength: 100));
            AlterColumn("dbo.AddressBooks", "State", c => c.String(maxLength: 50));
            AlterColumn("dbo.AddressBooks", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.AuditTrails", "ReferenceId", c => c.String(maxLength: 50));
            AlterColumn("dbo.AuditTrails", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Carriers", "Name", c => c.String(maxLength: 10));
            AlterColumn("dbo.Carriers", "CarrierNameLong", c => c.String(maxLength: 100));
            AlterColumn("dbo.Carriers", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.CarrierServices", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.CommercialInvoices", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.InvoiceItems", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.InvoiceItemLines", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Shipments", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShipmentAddresses", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShipmentPackages", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.PackageProducts", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShipmentPayments", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.CreditNotes", "CreditNoteNumber", c => c.String(maxLength: 100));
            AlterColumn("dbo.CreditNotes", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Invoices", "InvoiceNumber", c => c.String(maxLength: 50));
            AlterColumn("dbo.Invoices", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.InvoiceDisputeHistories", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.LocationActivities", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.ShipmentLocationHistories", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.NotificationCriterias", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.PaymentTypes", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Rates", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RateZones", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.Zones", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.TariffTypes", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.TransmitTimes", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.TransitTimeProducts", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.RoleHierarchies", "Name", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("dbo.RoleHierarchies", "ParentName", c => c.String(maxLength: 30));
            AlterColumn("dbo.ShipmentDocuments", "CreatedBy", c => c.String(maxLength: 50));
            AlterColumn("dbo.TarrifTextCodes", "CreatedBy", c => c.String(maxLength: 50));
            AddPrimaryKey("dbo.RoleHierarchies", "Name");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.RoleHierarchies");
            AlterColumn("dbo.TarrifTextCodes", "CreatedBy", c => c.String());
            AlterColumn("dbo.ShipmentDocuments", "CreatedBy", c => c.String());
            AlterColumn("dbo.RoleHierarchies", "ParentName", c => c.String());
            AlterColumn("dbo.RoleHierarchies", "Name", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TransitTimeProducts", "CreatedBy", c => c.String());
            AlterColumn("dbo.TransmitTimes", "CreatedBy", c => c.String());
            AlterColumn("dbo.TariffTypes", "CreatedBy", c => c.String());
            AlterColumn("dbo.Zones", "CreatedBy", c => c.String());
            AlterColumn("dbo.RateZones", "CreatedBy", c => c.String());
            AlterColumn("dbo.Rates", "CreatedBy", c => c.String());
            AlterColumn("dbo.PaymentTypes", "CreatedBy", c => c.String());
            AlterColumn("dbo.NotificationCriterias", "CreatedBy", c => c.String());
            AlterColumn("dbo.ShipmentLocationHistories", "CreatedBy", c => c.String());
            AlterColumn("dbo.LocationActivities", "CreatedBy", c => c.String());
            AlterColumn("dbo.InvoiceDisputeHistories", "CreatedBy", c => c.String());
            AlterColumn("dbo.Invoices", "CreatedBy", c => c.String());
            AlterColumn("dbo.Invoices", "InvoiceNumber", c => c.String());
            AlterColumn("dbo.CreditNotes", "CreatedBy", c => c.String());
            AlterColumn("dbo.CreditNotes", "CreditNoteNumber", c => c.String());
            AlterColumn("dbo.ShipmentPayments", "CreatedBy", c => c.String());
            AlterColumn("dbo.PackageProducts", "CreatedBy", c => c.String());
            AlterColumn("dbo.ShipmentPackages", "CreatedBy", c => c.String());
            AlterColumn("dbo.ShipmentAddresses", "CreatedBy", c => c.String());
            AlterColumn("dbo.Shipments", "CreatedBy", c => c.String());
            AlterColumn("dbo.InvoiceItemLines", "CreatedBy", c => c.String());
            AlterColumn("dbo.InvoiceItems", "CreatedBy", c => c.String());
            AlterColumn("dbo.CommercialInvoices", "CreatedBy", c => c.String());
            AlterColumn("dbo.CarrierServices", "CreatedBy", c => c.String());
            AlterColumn("dbo.Carriers", "CreatedBy", c => c.String());
            AlterColumn("dbo.Carriers", "CarrierNameLong", c => c.String());
            AlterColumn("dbo.Carriers", "Name", c => c.String());
            AlterColumn("dbo.AuditTrails", "CreatedBy", c => c.String());
            AlterColumn("dbo.AuditTrails", "ReferenceId", c => c.String());
            AlterColumn("dbo.AddressBooks", "CreatedBy", c => c.String());
            AlterColumn("dbo.AddressBooks", "State", c => c.String());
            AlterColumn("dbo.AddressBooks", "City", c => c.String());
            AlterColumn("dbo.AddressBooks", "Number", c => c.String());
            AlterColumn("dbo.AddressBooks", "ZipCode", c => c.String());
            AlterColumn("dbo.AddressBooks", "Country", c => c.String());
            AlterColumn("dbo.AddressBooks", "AccountNumber", c => c.String());
            AlterColumn("dbo.AddressBooks", "PhoneNumber", c => c.String());
            AlterColumn("dbo.AddressBooks", "EmailAddress", c => c.String());
            AlterColumn("dbo.AddressBooks", "LastName", c => c.String());
            AlterColumn("dbo.AddressBooks", "FirstName", c => c.String());
            AlterColumn("dbo.AddressBooks", "Salutation", c => c.String());
            AlterColumn("dbo.AddressBooks", "UserId", c => c.String());
            AlterColumn("dbo.AddressBooks", "CompanyName", c => c.String());
            AlterColumn("dbo.WeightMetrics", "CreatedBy", c => c.String());
            AlterColumn("dbo.WeightMetrics", "Name", c => c.String());
            AlterColumn("dbo.VolumeMetrics", "CreatedBy", c => c.String());
            AlterColumn("dbo.VolumeMetrics", "Name", c => c.String());
            AlterColumn("dbo.TimeZones", "CreatedBy", c => c.String());
            AlterColumn("dbo.Languages", "CreatedBy", c => c.String());
            AlterColumn("dbo.Languages", "LanguageName", c => c.String());
            AlterColumn("dbo.Languages", "LanguageCode", c => c.String());
            AlterColumn("dbo.Currencies", "CreatedBy", c => c.String());
            AlterColumn("dbo.Currencies", "CurrencyName", c => c.String());
            AlterColumn("dbo.Currencies", "CurrencyCode", c => c.String());
            AlterColumn("dbo.DivisionCostCenters", "CreatedBy", c => c.String());
            AlterColumn("dbo.CostCenters", "CreatedBy", c => c.String());
            AlterColumn("dbo.CostCenters", "Type", c => c.String());
            AlterColumn("dbo.CostCenters", "PhoneNumber", c => c.String());
            AlterColumn("dbo.CostCenters", "Name", c => c.String());
            AlterColumn("dbo.Companies", "CreatedBy", c => c.String());
            AlterColumn("dbo.Companies", "CompanyCode", c => c.String());
            AlterColumn("dbo.Companies", "VATNumber", c => c.String());
            AlterColumn("dbo.Companies", "COCNumber", c => c.String());
            AlterColumn("dbo.Companies", "Name", c => c.String());
            AlterColumn("dbo.Divisions", "CreatedBy", c => c.String());
            AlterColumn("dbo.Divisions", "Type", c => c.String());
            AlterColumn("dbo.Divisions", "Name", c => c.String());
            AlterColumn("dbo.UserInDivisions", "CreatedBy", c => c.String());
            AlterColumn("dbo.Tenants", "CreatedBy", c => c.String());
            AlterColumn("dbo.Tenants", "TenancyName", c => c.String());
            AlterColumn("dbo.Addresses", "CreatedBy", c => c.String());
            AlterColumn("dbo.Addresses", "State", c => c.String());
            AlterColumn("dbo.Addresses", "City", c => c.String());
            AlterColumn("dbo.Addresses", "Number", c => c.String());
            AlterColumn("dbo.Addresses", "ZipCode", c => c.String());
            AlterColumn("dbo.Addresses", "Country", c => c.String());
            AlterColumn("dbo.Customers", "CreatedBy", c => c.String());
            AlterColumn("dbo.Customers", "SelectedColour", c => c.String());
            AlterColumn("dbo.Customers", "JobCapacity", c => c.String());
            AlterColumn("dbo.Customers", "MobileNumber", c => c.String());
            AlterColumn("dbo.Customers", "PhoneNumber", c => c.String());
            AlterColumn("dbo.Customers", "SecondaryEmail", c => c.String());
            AlterColumn("dbo.Customers", "Email", c => c.String());
            AlterColumn("dbo.Customers", "LastName", c => c.String());
            AlterColumn("dbo.Customers", "MiddleName", c => c.String());
            AlterColumn("dbo.Customers", "FirstName", c => c.String());
            AlterColumn("dbo.Customers", "Salutation", c => c.String());
            AlterColumn("dbo.AccountSettings", "CreatedBy", c => c.String());
            AddPrimaryKey("dbo.RoleHierarchies", "Name");
        }
    }
}
