// <auto-generated />
namespace PI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updatepaymentwithamountandcurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatepaymentwithamountandcurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201610020528451_Update payment with amount and currency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
