// <auto-generated />
namespace PI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ph2Addcompanynametoshipmentaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ph2Addcompanynametoshipmentaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201606071247390_Ph2 - Add company name to shipment address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
